# Generated by Django 4.2.6 on 2023-10-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scodeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scodedetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bike_images/')),
                ('heading', models.CharField(blank=True, max_length=250, null=True)),
                ('para', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
